### ISSUE TITLE
[TP6] Exercice 2

### ISSUE THREAD

**Issue by aroty97** [BEAMS-EE/ELECH310#20]
Corriger les références des table 1-2-3 pour retirer le ??

**Comment by f380cedric** [comment]
Je ne trouve pas de problème de référence (ni localement, ni sur l'UV).
Aurais-tu compilé qu'une seule fois ? Il y a un Makefile pour gérer le nombre de compilation nécessaire pour résoudre les références.

**Comment by aroty97** [comment]
La version que j'ai est celle uploadée sur l'umons pour le cours donné au bachelier Charleroi, si il n'y a pas de soucis dans les sources alors il faut juste reuploader une version correctement compilée :)
